---
title: "Historical Analysis of Novels"
author: "Madison McCann"
date: "2025-12-08"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)

df <- read.csv("top-500-novels-metadata_2025-01-11.csv")

df <- df |>
  mutate(
    publication_century = case_when(
      pub_year <= 1700 ~ "17th Century and Earlier",
      pub_year <= 1800 ~ "18th Century",
      pub_year <= 1900 ~ "19th Century",
      pub_year <= 2000 ~ "20th Century",
      TRUE ~ "21st Century"
    )
  )

century_order <- c("17th Century and Earlier", "18th Century", "19th Century", "20th Century", "21st Century")
df$publication_century <- factor(df$publication_century, levels = century_order, ordered = TRUE)

df <- df |>
  mutate(
    oclc_holdings_clean = as.numeric(gsub(",", "", as.character(oclc_holdings))),
    gr_num_ratings_clean = as.numeric(gsub(",", "", gr_num_ratings))
  )

```

```{r}
#ANALYSIS QUESTION 1: How has the distribution of top-ranked novel's publication years changed over time?

century_counts <- df |>
  count(publication_century, name = "novel_count")

print("Novel Counts by Publication Century:")
print (century_counts)
```

```{r}
#VISUAL 1: BAR CHART OF NOVELS BY PUBLICATION CENTURY
pub_year_plot <- ggplot(century_counts, aes(x = publication_century, y = novel_count, fill = publication_century)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = novel_count), vjust = -0.5, size = 3) +
  labs(
    title = "Distribution of Top 500 Novels by Publication Century",
    x = "Publication Century",
    y = "Number of Novels",
    fill = "Century"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )

print(pub_year_plot)

ggsave("novels_by_century_bar_char.png", plot = pub_year_plot, width = 7, height = 5)

```

```{r}
#ANALYSIS QUESTION 2: Is there a relationship between a novel's genre and its Goodreads Average Rating?

top_genres <- df |>
  filter(genre != "") |> 
  count(genre, sort = TRUE)|>
  slice_head(n = 5)|>
  pull(genre)

df_top_genres <- df |>
  filter(genre %in% top_genres)

df_top_genres$genre <- factor(df_top_genres$genre, levels = rev(top_genres))


```

```{r}
#VISUAL 2: BOX PLOT OF AVERAGE RATING BY TOP 5 GENRE

genre_rating_plot <- ggplot(df_top_genres, aes(x = gr_avg_rating, y = genre, fill = genre)) +
  geom_boxplot() +
  labs(
    title = "Goodreads Average Rating Distribtuion for Top 5 Genres",
    x = "Goodreads Average Rating",
    y = "Genre",
    fill = "genre"
  ) +
  scale_x_continuous(limits = c(3.5, 4.5), breaks = seq(3.5, 4.5, 0.1)) +
  theme_minimal() +
  theme(legend.position = "none")

print(genre_rating_plot)

ggsave("avg_rating_by_top_genre_boxplot.png", plot = genre_rating_plot, width = 7, height = 5)

```

```{r}
#ANALYSIS QUESTION 3: Has the original language of the top novels shifted over time?

languages_of_interest <- c("English", "French", "Russian", "German", "Spanish")

df_lang_grouped <- df |>
  mutate(
    orig_lang_grouped = case_when(
      orig_lang %in% languages_of_interest ~ orig_lang,
      TRUE ~ "Other"
    )
  )

lang_century_counts <- df_lang_grouped |>
  group_by(publication_century, orig_lang_grouped) |>
  count(name = "novel_count") |>
  ungroup() 

```

```{r}
#VISUAL 3: STACKED BAR CHART OF LANGUAGE BY PUBLICATION CENTURY

lang_dominance_plot <- ggplot(lang_century_counts, aes(x = publication_century, y = novel_count, fill = orig_lang_grouped)) +
  geom_bar(stat = "identity", position =  "stack") +
  labs(
    title = "Original Language Distribution of Top Novels by Century",
    subtitle = "English-language novels dominate from the 20th Century onwards.",
    x = "Publication Century",
    y = "Number of Novels",
    fill = "Original Language"
  ) +
  scale_fill_brewer(palette = "Set2") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

print(lang_dominance_plot)

ggsave("lang_dominance_by_century_stacked_bar.png", plot = lang_dominance_plot, width = 8, height = 6)

```
```{r}
#ANALYSIS QUESTION 4: Does the average rating (gr_avg_rating) or library holdings (oclc_holdings) correlate with age (pub_year)?

#VISUAL 4A: SCATTER PLOT OF PUBLICATION YEAR VS GOODREADS AVERAGE RATING
age_rating_plot <- ggplot(df, aes(x = pub_year, y = gr_avg_rating)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", col = "purple") +
  labs(
    title = "Goodreads Average Rating vs. Publication Year",
    subtitle = "A slight trend suggests older books may have higher average ratings. ",
    x = "Publication Year",
    y = "Goodreads Average Rating"
  ) + 
  theme_minimal()

print(age_rating_plot)
ggsave("age_vs_avg_rating_scatter.png", plot = age_rating_plot, width = 7, height = 5
       )
```

```{r}
#VISUAL 4B: SCATTER PLOT OF PUBLICATION YEAR VS. OCLC HOLDINGS

age_holdings_plot <- ggplot(df, aes (x = pub_year, y = oclc_holdings_clean)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", col = "red") +
  scale_y_continuous(labels = scales::comma) +
  labs(
    title = "OCLC Holdings vs. Publication Year",
    subtitle = "OCLC Holdings are generally higher for older books, suggesting they have 'stood the test of time'.",
    x = "Publication Year",
    y = "OCLC Holdings (Number of Libraries Holding the Book)"
  ) +
  theme_minimal()

print(age_holdings_plot)
ggsave("age_vs_holdings_scatter.png", plot = age_holdings_plot, width = 7, height = 5)

```

```{r}
# ANALYSIS QUESTION 5: How has the number of Goodreads rating for top-ranked novels changed over time, and what is the distribution of the top-ranked novel's publication years by genre?

# VISUAL 5A: SCATTER PLOT OF PUBLICATION YEAR VS GOODREADS NUMBER OF RATINGS (gr_num_ratings_clean)

age_ratings_count_plot <- ggplot(df, aes(x = pub_year, y = gr_num_ratings_clean)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", col = "darkred") +
  scale_y_continuous(labels = scales::comma) +
  labs(
    title = "Goodreads Total Number of Ratings vs. Publication Year",
    subtitle = "Newer books tend to have a higher count of total ratings, indicating greater recent popularity.",
    x = "Publication Year",
    y = "Goodreads Total Number of Ratings"
  ) +
  theme_minimal()
  
  print(age_ratings_count_plot)
  
  ggsave("scatter_publication_goodreads.png", plot = age_ratings_count_plot, width = 7, height = 5)
```

```{r}
# VISUAL 5B: DISTRIBUTION OF PUBLICATION CENTURY BY TOP 5 GENRES

genre_century_counts <- df_top_genres |>
  group_by(publication_century, genre) |>
  count(name = "novel_count") |>
  ungroup()

genre_century_plot <- ggplot(genre_century_counts, aes(x = publication_century, y = novel_count, fill = genre)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(
    title = "Distribution of Top 5 Genres by Publication Century",
    subtitle = "Certain genres show concentrations in specific centuries.",
    x = "Publication Century",
    y = "Number of Novels",
    fill = "Genre"
  ) +
  scale_fill_brewer(palette = "Set1") + 
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

print(genre_century_plot)

ggsave("distrib_top_genres_bar.png", plot = genre_century_plot, width = 7, height = 5)

```
```{r}
# ANALYSIS QUESTION 6: Is there a correlation between a novel's long-term institutional recognition (OCLC Holdings) and its modern-day popularity (Goodreads Total Ratings)?

correlation_output <- df |>
  summarise(
    correlation = cor(oclc_holdings_clean, gr_num_ratings_clean, use = "complete.obs")
  )
print("Correlation between OCLC Holdings and Goodreads Total Ratings:")
print(correlation_output)

```

```{r}
# VISUAL 6: SCATTER PLOT OF OCLC HOLDINGS VS. GOODREADS TOTAL RATINGS
holdings_vs_ratings_plot <- ggplot(df, aes(x = oclc_holdings_clean, y = gr_num_ratings_clean)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", col = "blue") +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma) +
  labs(
    title = "OCLC Holdings vs. Goodreads Total Ratings",
    subtitle = "A moderate positive correlation suggests that historically recognized books also achieve modern mass appeal.",
    x = "OCLC Holdings (Number of Libraries Holding the Book)",
    y = "Goodreads Total Number of Ratings"
  ) +
  theme_minimal()

print(holdings_vs_ratings_plot)
# Corrected plot object name:
ggsave("scatter_holdings_goodread_ratings.png", plot = holdings_vs_ratings_plot, width = 7, height = 5)
```

